// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Question struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	SeminarID uuid.UUID
	Question  string
}

type Seminar struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Name       string
	ApiKey     string
	UserID     uuid.UUID
	ExpiryDate time.Time
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	FullName  string
	Email     string
	Password  string
	Role      string
}
